name: Main Workflow

on:
  - push
  - pull_request

jobs:
  types:
    name: Check Types
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4.2.2
      - uses: pnpm/action-setup@v4.1.0
        with:
          version: 10.9.0
          run_install: false
      - uses: actions/setup-node@4.4.0
        with:
          node-version: 23.11.1
          cache: "pnpm"

      - run: pnpm install
      - run: pnpm types

  lint:
    name: Check Linting
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4.2.2
      - uses: pnpm/action-setup@v4.1.0
        with:
          version: 10.9.0
          run_install: false
      - uses: actions/setup-node@4.4.0
        with:
          node-version: 23.11.1
          cache: "pnpm"

      - run: pnpm install
      - run: pnpm lint

  test:
    name: Test
    runs-on: ubuntu-24.04
    needs:
      - types
      - lint

    steps:
      - uses: actions/checkout@v4.2.2
      - uses: pnpm/action-setup@v4.1.0
        with:
          version: 10.9.0
          run_install: false
      - uses: actions/setup-node@4.4.0
        with:
          node-version: 23.11.1
          cache: "pnpm"

      - run: pnpm install
      - run: pnpm test

  build:
    name: Build
    runs-on: ubuntu-24.04
    needs:
      - test

    steps:
      - uses: actions/checkout@v4.2.2
      - uses: pnpm/action-setup@v4.1.0
        with:
          version: 10.9.0
          run_install: false
      - uses: actions/setup-node@4.4.0
        with:
          node-version: 23.11.1
          cache: "pnpm"

      - run: pnpm install
      - run: pnpm build
